// User
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'

// Goals
export const GET_ALL_GOALS = 'GET_ALL_GOALS'
export const CREATE_NEW_GOAL = 'CREATE_NEW_GOAL'
export const ERROR_CREATING_GOAL = 'ERROR_CREATING_GOAL'
export const UPDATE_GOAL = 'UPDATE_GOAL'
export const DELETE_GOAL = 'DELETE_GOAL'
export const CREATE_NEW_FINISHED_GOAL = 'CREATE_NEW_FINISHED_GOAL'

// Group
export const CREATE_NEW_GROUP = 'CREATE_NEW_GROUP'
export const ERROR_CREATING_GROUP = 'ERROR_CREATING_GROUP'
export const UPDATE_GROUP = 'UPDATE_GROUP'
export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'
export const CREATE_NEW_GROUP_MESSAGE = 'CREATE_NEW_GROUP_MESSAGE'
export const GET_ALL_GROUP_MESSAGE = 'GET_ALL_GROUP_MESSAGE'