// User
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_ERROR = 'LOGOUT_ERROR'
export const GET_USER = 'GET_USER'

// Goals
export const GET_ALL_GOALS = 'GET_ALL_GOALS'
export const GET_DEFAULT_GOALS = 'GET_DEFAULT_GOALS'
export const CREATE_NEW_GOAL = 'CREATE_NEW_GOAL'
export const CREATE_CUSTOM_GOAL = 'CREATE_CUSTOM_GOAL'
export const ERROR_CREATING_GOAL = 'ERROR_CREATING_GOAL'
export const UPDATE_GOAL = 'UPDATE_GOAL'
export const DELETE_GOAL = 'DELETE_GOAL'
export const CREATE_NEW_FINISHED_GOAL = 'CREATE_NEW_FINISHED_GOAL'
export const GET_CUSTOM_GOAL = 'GET_CUSTOM_GOAL'
export const GET_CUSTOM_GOALS_BY_GROUPID_ARRAY = 'GET_CUSTOM_GOALS_BY_GROUPID_ARRAY'
export const FINISHED_GOAL_SELECTED = 'FINISHED_GOAL_SELECTED'
export const FINSIHED_GOAL_FORM_CLOSED = 'FINSIHED_GOAL_FORM_CLOSED'

// Group
export const CREATE_NEW_GROUP = 'CREATE_NEW_GROUP'
export const ERROR_CREATING_GROUP = 'ERROR_CREATING_GROUP'
export const UPDATE_GROUP = 'UPDATE_GROUP'
export const ADD_USER_TO_GROUP = 'ADD_USER_TO_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'
export const GET_ALL_USERS_GROUPS = 'GET_ALL_USERS_GROUPS'
export const GET_ALL_GROUPS_FULL_DATA = 'GET_ALL_GROUPS_FULL_DATA'
export const UPDATE_GROUP_SCORES = 'UPDATE_GROUP_SCORES'

// Group Messages
export const CREATE_NEW_GROUP_MESSAGE = 'CREATE_NEW_GROUP_MESSAGE'
export const GET_ALL_GROUP_MESSAGE = 'GET_ALL_GROUP_MESSAGE'